;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 4/6/2008 14:06:31
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;SwitchTest.c,1 :: 		void main()
;SwitchTest.c,3 :: 		ANSELH.F4=0;                 // RA4 ==> Digital IO
$0004	$1703			BSF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$1209			BCF	ANSELH, 4
;SwitchTest.c,4 :: 		TRISB.F3=0;                  // RB3 ==> Digital Output
$0007	$1303			BCF	STATUS, RP1
$0008	$1186			BCF	TRISB, 3
;SwitchTest.c,5 :: 		while(1)                     // Infinite Loop
$0009	$	L_main_0:
;SwitchTest.c,7 :: 		if(PORTB.F0==0)         // Check RB0 Press ?
$0009	$3001			MOVLW	1
$000A	$1283			BCF	STATUS, RP0
$000B	$0506			ANDWF	PORTB, 0
$000C	$00F1			MOVWF	STACK_1
$000D	$0871			MOVF	STACK_1, 0
$000E	$3A00			XORLW	0
$000F	$1D03			BTFSS	STATUS, Z
$0010	$2812			GOTO	L_main_2
;SwitchTest.c,9 :: 		PORTB.F3=1;        // ON ==> RB3
$0011	$1586			BSF	PORTB, 3
;SwitchTest.c,10 :: 		}
$0012	$	L_main_2:
;SwitchTest.c,11 :: 		if(PORTA.F4==0)         // Check RA4 Press ?
$0012	$3000			MOVLW	0
$0013	$1A05			BTFSC	PORTA, 4
$0014	$3001			MOVLW	1
$0015	$00F1			MOVWF	STACK_1
$0016	$0871			MOVF	STACK_1, 0
$0017	$3A00			XORLW	0
$0018	$1D03			BTFSS	STATUS, Z
$0019	$281B			GOTO	L_main_3
;SwitchTest.c,13 :: 		PORTB.F3=0;        // OFF ==> RB3
$001A	$1186			BCF	PORTB, 3
;SwitchTest.c,14 :: 		}
$001B	$	L_main_3:
;SwitchTest.c,15 :: 		}
$001B	$2809			GOTO	L_main_0
;SwitchTest.c,16 :: 		}
$001C	$281C			GOTO	$
